
development:
  adapter: postgresql
  encoding: unicode
  database: AppName_development
  pool: 5
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: AppName_test
  pool: 5
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: AppName_production
  pool: 5
  password:
